// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    id, task_id, actor_id, actor_type, type, content, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, task_id, actor_id, actor_type, type, content, created_at
`

type CreateActivityParams struct {
	ID        string         `json:"id"`
	TaskID    sql.NullString `json:"task_id"`
	ActorID   sql.NullString `json:"actor_id"`
	ActorType sql.NullString `json:"actor_type"`
	Type      sql.NullString `json:"type"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.ID,
		arg.TaskID,
		arg.ActorID,
		arg.ActorType,
		arg.Type,
		arg.Content,
		arg.CreatedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ActorID,
		&i.ActorType,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listActivitiesByTask = `-- name: ListActivitiesByTask :many
SELECT id, task_id, actor_id, actor_type, type, content, created_at FROM activities
WHERE task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListActivitiesByTask(ctx context.Context, taskID sql.NullString) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.ActorType,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
