// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: areas.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createArea = `-- name: CreateArea :one
INSERT INTO areas (
    id, title, "index", archived, deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, 0, 0, NULL, ?, ?
)
RETURNING id, title, "index", archived, deleted, deleted_at, created_at, updated_at
`

type CreateAreaParams struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	Index     int64          `json:"index"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error) {
	row := q.db.QueryRowContext(ctx, createArea,
		arg.ID,
		arg.Title,
		arg.Index,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Index,
		&i.Archived,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArea = `-- name: GetArea :one
SELECT id, title, "index", archived, deleted, deleted_at, created_at, updated_at FROM areas
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetArea(ctx context.Context, id string) (Area, error) {
	row := q.db.QueryRowContext(ctx, getArea, id)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Index,
		&i.Archived,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllAreas = `-- name: ListAllAreas :many
SELECT id, title, "index", archived, deleted, deleted_at, created_at, updated_at FROM areas
WHERE deleted = 0
ORDER BY "index"
`

func (q *Queries) ListAllAreas(ctx context.Context) ([]Area, error) {
	rows, err := q.db.QueryContext(ctx, listAllAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Area{}
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Index,
			&i.Archived,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAreas = `-- name: ListAreas :many
SELECT id, title, "index", archived, deleted, deleted_at, created_at, updated_at FROM areas
WHERE deleted = 0 AND archived = 0
ORDER BY "index"
`

func (q *Queries) ListAreas(ctx context.Context) ([]Area, error) {
	rows, err := q.db.QueryContext(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Area{}
	for rows.Next() {
		var i Area
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Index,
			&i.Archived,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArea = `-- name: SoftDeleteArea :exec
UPDATE areas SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteAreaParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteArea, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateAreaArchived = `-- name: UpdateAreaArchived :one
UPDATE areas SET archived = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, "index", archived, deleted, deleted_at, created_at, updated_at
`

type UpdateAreaArchivedParams struct {
	Archived  int64     `json:"archived"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateAreaArchived(ctx context.Context, arg UpdateAreaArchivedParams) (Area, error) {
	row := q.db.QueryRowContext(ctx, updateAreaArchived, arg.Archived, arg.UpdatedAt, arg.ID)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Index,
		&i.Archived,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAreaTitle = `-- name: UpdateAreaTitle :one
UPDATE areas SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, "index", archived, deleted, deleted_at, created_at, updated_at
`

type UpdateAreaTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateAreaTitle(ctx context.Context, arg UpdateAreaTitleParams) (Area, error) {
	row := q.db.QueryRowContext(ctx, updateAreaTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Area
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Index,
		&i.Archived,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
