// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, user_id, name, key_hash, permissions, scope, expires_at, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL)
RETURNING id, user_id, name, key_hash, permissions, scope, expires_at, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Name        sql.NullString `json:"name"`
	KeyHash     sql.NullString `json:"key_hash"`
	Permissions string         `json:"permissions"`
	Scope       string         `json:"scope"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Permissions,
		arg.Scope,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Permissions,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, permissions, scope, expires_at, created_at, last_used_at FROM api_keys
WHERE key_hash = ? AND (expires_at IS NULL OR expires_at > datetime('now'))
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash sql.NullString) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Permissions,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, key_hash, permissions, scope, expires_at, created_at, last_used_at FROM api_keys WHERE user_id = ?
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Permissions,
			&i.Scope,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :one
UPDATE api_keys SET name = ? WHERE id = ?
RETURNING id, user_id, name, key_hash, permissions, scope, expires_at, created_at, last_used_at
`

type UpdateAPIKeyNameParams struct {
	Name sql.NullString `json:"name"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKeyName, arg.Name, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Permissions,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
