// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checklist_items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countChecklistByTask = `-- name: CountChecklistByTask :one
SELECT
    COUNT(*) AS total,
    COUNT(CASE WHEN status = 1 THEN 1 END) AS done
FROM checklist_items
WHERE task_id = ? AND deleted = 0
`

type CountChecklistByTaskRow struct {
	Total int64 `json:"total"`
	Done  int64 `json:"done"`
}

func (q *Queries) CountChecklistByTask(ctx context.Context, taskID sql.NullString) (CountChecklistByTaskRow, error) {
	row := q.db.QueryRowContext(ctx, countChecklistByTask, taskID)
	var i CountChecklistByTaskRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (
    id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, 0, NULL, ?, ?
)
RETURNING id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at
`

type CreateChecklistItemParams struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	Status    int64          `json:"status"`
	TaskID    sql.NullString `json:"task_id"`
	Index     int64          `json:"index"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, createChecklistItem,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.TaskID,
		arg.Index,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.TaskID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at FROM checklist_items
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetChecklistItem(ctx context.Context, id string) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.TaskID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecklistItemsByTask = `-- name: ListChecklistItemsByTask :many
SELECT id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at FROM checklist_items
WHERE task_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListChecklistItemsByTask(ctx context.Context, taskID sql.NullString) ([]ChecklistItem, error) {
	rows, err := q.db.QueryContext(ctx, listChecklistItemsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.TaskID,
			&i.Index,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChecklistItem = `-- name: SoftDeleteChecklistItem :exec
UPDATE checklist_items SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteChecklistItemParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteChecklistItem(ctx context.Context, arg SoftDeleteChecklistItemParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteChecklistItem, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateChecklistItemStatus = `-- name: UpdateChecklistItemStatus :one
UPDATE checklist_items SET status = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at
`

type UpdateChecklistItemStatusParams struct {
	Status    int64     `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateChecklistItemStatus(ctx context.Context, arg UpdateChecklistItemStatusParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistItemStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.TaskID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChecklistItemTitle = `-- name: UpdateChecklistItemTitle :one
UPDATE checklist_items SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, status, task_id, "index", deleted, deleted_at, created_at, updated_at
`

type UpdateChecklistItemTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateChecklistItemTitle(ctx context.Context, arg UpdateChecklistItemTitleParams) (ChecklistItem, error) {
	row := q.db.QueryRowContext(ctx, updateChecklistItemTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.TaskID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
