// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertDeltaEvent = `-- name: InsertDeltaEvent :exec
INSERT INTO delta_events (
    entity_type, entity_id, action, field, old_value, new_value, actor_id, timestamp, user_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertDeltaEventParams struct {
	EntityType sql.NullString `json:"entity_type"`
	EntityID   sql.NullString `json:"entity_id"`
	Action     sql.NullInt64  `json:"action"`
	Field      sql.NullString `json:"field"`
	OldValue   sql.NullString `json:"old_value"`
	NewValue   sql.NullString `json:"new_value"`
	ActorID    sql.NullString `json:"actor_id"`
	Timestamp  sql.NullTime   `json:"timestamp"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) InsertDeltaEvent(ctx context.Context, arg InsertDeltaEventParams) error {
	_, err := q.db.ExecContext(ctx, insertDeltaEvent,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.ActorID,
		arg.Timestamp,
		arg.UserID,
	)
	return err
}

const insertDomainEvent = `-- name: InsertDomainEvent :one
INSERT INTO domain_events (
    type, entity_type, entity_id, actor_id, payload, timestamp, user_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertDomainEventParams struct {
	Type       sql.NullString `json:"type"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   sql.NullString `json:"entity_id"`
	ActorID    sql.NullString `json:"actor_id"`
	Payload    string         `json:"payload"`
	Timestamp  sql.NullTime   `json:"timestamp"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDomainEvent,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Payload,
		arg.Timestamp,
		arg.UserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDeltaEventsSince = `-- name: ListDeltaEventsSince :many
SELECT id, entity_type, entity_id, "action", field, old_value, new_value, actor_id, timestamp, user_id FROM delta_events
WHERE id > ? AND user_id = ?
ORDER BY id
`

type ListDeltaEventsSinceParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListDeltaEventsSince(ctx context.Context, arg ListDeltaEventsSinceParams) ([]DeltaEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDeltaEventsSince, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeltaEvent{}
	for rows.Next() {
		var i DeltaEvent
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.ActorID,
			&i.Timestamp,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainEventsByEntitySince = `-- name: ListDomainEventsByEntitySince :many
SELECT id, type, entity_type, entity_id, actor_id, payload, timestamp, user_id FROM domain_events
WHERE entity_type = ? AND entity_id = ? AND id > ? AND user_id = ?
ORDER BY id
`

type ListDomainEventsByEntitySinceParams struct {
	EntityType sql.NullString `json:"entity_type"`
	EntityID   sql.NullString `json:"entity_id"`
	ID         int64          `json:"id"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) ListDomainEventsByEntitySince(ctx context.Context, arg ListDomainEventsByEntitySinceParams) ([]DomainEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDomainEventsByEntitySince,
		arg.EntityType,
		arg.EntityID,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Payload,
			&i.Timestamp,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainEventsByTypeSince = `-- name: ListDomainEventsByTypeSince :many
SELECT id, type, entity_type, entity_id, actor_id, payload, timestamp, user_id FROM domain_events
WHERE type = ? AND id > ? AND user_id = ?
ORDER BY id
`

type ListDomainEventsByTypeSinceParams struct {
	Type   sql.NullString `json:"type"`
	ID     int64          `json:"id"`
	UserID string         `json:"user_id"`
}

func (q *Queries) ListDomainEventsByTypeSince(ctx context.Context, arg ListDomainEventsByTypeSinceParams) ([]DomainEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDomainEventsByTypeSince, arg.Type, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Payload,
			&i.Timestamp,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainEventsSince = `-- name: ListDomainEventsSince :many
SELECT id, type, entity_type, entity_id, actor_id, payload, timestamp, user_id FROM domain_events
WHERE id > ? AND user_id = ?
ORDER BY id
`

type ListDomainEventsSinceParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListDomainEventsSince(ctx context.Context, arg ListDomainEventsSinceParams) ([]DomainEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDomainEventsSince, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Payload,
			&i.Timestamp,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
