// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const claimInvite = `-- name: ClaimInvite :execrows
UPDATE invites SET claimed_at = ? WHERE id = ? AND claimed_at IS NULL
`

type ClaimInviteParams struct {
	ClaimedAt sql.NullTime `json:"claimed_at"`
	ID        string       `json:"id"`
}

// claimed_at IS NULL makes this a single-use compare-and-swap: a second,
// concurrent claim affects 0 rows (see AuthService.ClaimInvite).
func (q *Queries) ClaimInvite(ctx context.Context, arg ClaimInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimInvite, arg.ClaimedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, email, role, token, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, email, role, token, created_by, created_at, claimed_at, expires_at
`

type CreateInviteParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, email, role, token, created_by, created_at, claimed_at, expires_at FROM invites
WHERE token = ? AND claimed_at IS NULL AND expires_at > datetime('now')
`

// expires_at > datetime('now') is a defense-in-depth clause only; the
// authoritative expiry check is done in Go (see AuthService.ValidateInviteToken).
func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, email, role, token, created_by, created_at, claimed_at, expires_at FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
