// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clearLocationFromTasks = `-- name: ClearLocationFromTasks :exec
UPDATE tasks SET location_id = NULL, updated_at = ?
WHERE location_id = ? AND user_id = ? AND deleted = 0
`

type ClearLocationFromTasksParams struct {
	UpdatedAt  time.Time      `json:"updated_at"`
	LocationID sql.NullString `json:"location_id"`
	UserID     string         `json:"user_id"`
}

func (q *Queries) ClearLocationFromTasks(ctx context.Context, arg ClearLocationFromTasksParams) error {
	_, err := q.db.ExecContext(ctx, clearLocationFromTasks, arg.UpdatedAt, arg.LocationID, arg.UserID)
	return err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
    id, name, latitude, longitude, radius, address, deleted, deleted_at, created_at, updated_at, user_id
) VALUES (
    ?, ?, ?, ?, ?, ?, 0, NULL, ?, ?, ?
)
RETURNING id, name, latitude, longitude, radius, address, deleted, deleted_at, created_at, updated_at, user_id
`

type CreateLocationParams struct {
	ID        string          `json:"id"`
	Name      sql.NullString  `json:"name"`
	Latitude  sql.NullFloat64 `json:"latitude"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Radius    sql.NullInt64   `json:"radius"`
	Address   sql.NullString  `json:"address"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	UserID    string          `json:"user_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.Radius,
		arg.Address,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Radius,
		&i.Address,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, latitude, longitude, radius, address, deleted, deleted_at, created_at, updated_at, user_id FROM locations
WHERE id = ? AND user_id = ? AND deleted = 0
`

type GetLocationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, arg.ID, arg.UserID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Radius,
		&i.Address,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, latitude, longitude, radius, address, deleted, deleted_at, created_at, updated_at, user_id FROM locations
WHERE user_id = ? AND deleted = 0
`

func (q *Queries) ListLocations(ctx context.Context, userID string) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.Radius,
			&i.Address,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLocation = `-- name: SoftDeleteLocation :exec
UPDATE locations SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type SoftDeleteLocationParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
}

func (q *Queries) SoftDeleteLocation(ctx context.Context, arg SoftDeleteLocationParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteLocation,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateLocationName = `-- name: UpdateLocationName :one
UPDATE locations SET name = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted = 0
RETURNING id, name, latitude, longitude, radius, address, deleted, deleted_at, created_at, updated_at, user_id
`

type UpdateLocationNameParams struct {
	Name      sql.NullString `json:"name"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
}

func (q *Queries) UpdateLocationName(ctx context.Context, arg UpdateLocationNameParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocationName,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Radius,
		&i.Address,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
