// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID        string         `json:"id"`
	TaskID    sql.NullString `json:"task_id"`
	ActorID   sql.NullString `json:"actor_id"`
	ActorType sql.NullString `json:"actor_type"`
	Type      sql.NullString `json:"type"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UserID    string         `json:"user_id"`
}

type ApiKey struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Name        sql.NullString `json:"name"`
	KeyHash     sql.NullString `json:"key_hash"`
	Permissions string         `json:"permissions"`
	Scope       string         `json:"scope"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	LastUsedAt  sql.NullTime   `json:"last_used_at"`
}

type Area struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	Index     int64          `json:"index"`
	Archived  int64          `json:"archived"`
	Deleted   int64          `json:"deleted"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	UserID    string         `json:"user_id"`
}

type ChecklistItem struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	Status    int64          `json:"status"`
	TaskID    sql.NullString `json:"task_id"`
	Index     int64          `json:"index"`
	Deleted   int64          `json:"deleted"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	UserID    string         `json:"user_id"`
}

type DeltaEvent struct {
	ID         int64          `json:"id"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   sql.NullString `json:"entity_id"`
	Action     sql.NullInt64  `json:"action"`
	Field      sql.NullString `json:"field"`
	OldValue   sql.NullString `json:"old_value"`
	NewValue   sql.NullString `json:"new_value"`
	ActorID    sql.NullString `json:"actor_id"`
	Timestamp  sql.NullTime   `json:"timestamp"`
	UserID     string         `json:"user_id"`
}

type DomainEvent struct {
	ID         int64          `json:"id"`
	Type       sql.NullString `json:"type"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   sql.NullString `json:"entity_id"`
	ActorID    sql.NullString `json:"actor_id"`
	Payload    string         `json:"payload"`
	Timestamp  sql.NullTime   `json:"timestamp"`
	UserID     string         `json:"user_id"`
}

type Invite struct {
	ID        string       `json:"id"`
	Email     string       `json:"email"`
	Role      string       `json:"role"`
	Token     string       `json:"token"`
	CreatedBy string       `json:"created_by"`
	CreatedAt time.Time    `json:"created_at"`
	ClaimedAt sql.NullTime `json:"claimed_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type Location struct {
	ID        string          `json:"id"`
	Name      sql.NullString  `json:"name"`
	Latitude  sql.NullFloat64 `json:"latitude"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Radius    sql.NullInt64   `json:"radius"`
	Address   sql.NullString  `json:"address"`
	Deleted   int64           `json:"deleted"`
	DeletedAt sql.NullTime    `json:"deleted_at"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	UserID    string          `json:"user_id"`
}

type Project struct {
	ID           string         `json:"id"`
	Title        sql.NullString `json:"title"`
	Notes        string         `json:"notes"`
	Status       int64          `json:"status"`
	Schedule     int64          `json:"schedule"`
	StartDate    sql.NullString `json:"start_date"`
	Deadline     sql.NullString `json:"deadline"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	Index        int64          `json:"index"`
	AreaID       sql.NullString `json:"area_id"`
	AutoComplete int64          `json:"auto_complete"`
	Deleted      int64          `json:"deleted"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Color        string         `json:"color"`
	UserID       string         `json:"user_id"`
}

type ProjectTag struct {
	ProjectID string `json:"project_id"`
	TagID     string `json:"tag_id"`
	UserID    string `json:"user_id"`
}

type Section struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	ProjectID sql.NullString `json:"project_id"`
	Index     int64          `json:"index"`
	Deleted   int64          `json:"deleted"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Archived  int64          `json:"archived"`
	Collapsed int64          `json:"collapsed"`
	UserID    string         `json:"user_id"`
}

type Tag struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	ParentID  sql.NullString `json:"parent_id"`
	Shortcut  sql.NullString `json:"shortcut"`
	Index     int64          `json:"index"`
	Deleted   int64          `json:"deleted"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	UserID    string         `json:"user_id"`
}

type Task struct {
	ID             string         `json:"id"`
	Title          sql.NullString `json:"title"`
	Notes          string         `json:"notes"`
	Status         int64          `json:"status"`
	Schedule       int64          `json:"schedule"`
	StartDate      sql.NullString `json:"start_date"`
	Deadline       sql.NullString `json:"deadline"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	Index          int64          `json:"index"`
	TodayIndex     sql.NullInt64  `json:"today_index"`
	ProjectID      sql.NullString `json:"project_id"`
	SectionID      sql.NullString `json:"section_id"`
	AreaID         sql.NullString `json:"area_id"`
	LocationID     sql.NullString `json:"location_id"`
	RecurrenceRule sql.NullString `json:"recurrence_rule"`
	Deleted        int64          `json:"deleted"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	TimeSlot       sql.NullString `json:"time_slot"`
	UserID         string         `json:"user_id"`
}

type TaskLink struct {
	TaskID           string       `json:"task_id"`
	RelatedTaskID    string       `json:"related_task_id"`
	RelationshipType string       `json:"relationship_type"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UserID           string       `json:"user_id"`
}

type TaskTag struct {
	TaskID string `json:"task_id"`
	TagID  string `json:"tag_id"`
	UserID string `json:"user_id"`
}
