// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const cascadeDeleteProjectsByArea = `-- name: CascadeDeleteProjectsByArea :exec
UPDATE projects SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE area_id = ? AND deleted = 0
`

type CascadeDeleteProjectsByAreaParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	AreaID    sql.NullString `json:"area_id"`
}

func (q *Queries) CascadeDeleteProjectsByArea(ctx context.Context, arg CascadeDeleteProjectsByAreaParams) error {
	_, err := q.db.ExecContext(ctx, cascadeDeleteProjectsByArea, arg.DeletedAt, arg.UpdatedAt, arg.AreaID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, title, notes, status, schedule, start_date, deadline, completed_at,
    "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, 0, NULL, ?, ?
)
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type CreateProjectParams struct {
	ID           string         `json:"id"`
	Title        sql.NullString `json:"title"`
	Notes        string         `json:"notes"`
	Status       int64          `json:"status"`
	Schedule     int64          `json:"schedule"`
	StartDate    sql.NullString `json:"start_date"`
	Deadline     sql.NullString `json:"deadline"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	Index        int64          `json:"index"`
	AreaID       sql.NullString `json:"area_id"`
	AutoComplete int64          `json:"auto_complete"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Status,
		arg.Schedule,
		arg.StartDate,
		arg.Deadline,
		arg.CompletedAt,
		arg.Index,
		arg.AreaID,
		arg.AutoComplete,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at FROM projects
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at FROM projects
WHERE deleted = 0
ORDER BY "index"
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.AreaID,
			&i.AutoComplete,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByArea = `-- name: ListProjectsByArea :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at FROM projects
WHERE area_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListProjectsByArea(ctx context.Context, areaID sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByArea, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.AreaID,
			&i.AutoComplete,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanProjectsByArea = `-- name: OrphanProjectsByArea :exec
UPDATE projects SET area_id = NULL, updated_at = ?
WHERE area_id = ? AND deleted = 0
`

type OrphanProjectsByAreaParams struct {
	UpdatedAt time.Time      `json:"updated_at"`
	AreaID    sql.NullString `json:"area_id"`
}

func (q *Queries) OrphanProjectsByArea(ctx context.Context, arg OrphanProjectsByAreaParams) error {
	_, err := q.db.ExecContext(ctx, orphanProjectsByArea, arg.UpdatedAt, arg.AreaID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteProjectParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteProject, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateProjectArea = `-- name: UpdateProjectArea :one
UPDATE projects SET area_id = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type UpdateProjectAreaParams struct {
	AreaID    sql.NullString `json:"area_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateProjectArea(ctx context.Context, arg UpdateProjectAreaParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectArea, arg.AreaID, arg.UpdatedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectDeadline = `-- name: UpdateProjectDeadline :one
UPDATE projects SET deadline = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type UpdateProjectDeadlineParams struct {
	Deadline  sql.NullString `json:"deadline"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateProjectDeadline(ctx context.Context, arg UpdateProjectDeadlineParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectDeadline, arg.Deadline, arg.UpdatedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectNotes = `-- name: UpdateProjectNotes :one
UPDATE projects SET notes = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type UpdateProjectNotesParams struct {
	Notes     string    `json:"notes"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateProjectNotes(ctx context.Context, arg UpdateProjectNotesParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectNotes, arg.Notes, arg.UpdatedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects SET status = ?, completed_at = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	Status      int64        `json:"status"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectStatus,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectTitle = `-- name: UpdateProjectTitle :one
UPDATE projects SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", area_id, auto_complete, deleted, deleted_at, created_at, updated_at
`

type UpdateProjectTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateProjectTitle(ctx context.Context, arg UpdateProjectTitleParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.AreaID,
		&i.AutoComplete,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
