// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sections.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSection = `-- name: CreateSection :one
INSERT INTO sections (
    id, title, project_id, "index", deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, 0, NULL, ?, ?
)
RETURNING id, title, project_id, "index", deleted, deleted_at, created_at, updated_at
`

type CreateSectionParams struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	ProjectID sql.NullString `json:"project_id"`
	Index     int64          `json:"index"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, createSection,
		arg.ID,
		arg.Title,
		arg.ProjectID,
		arg.Index,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSection = `-- name: GetSection :one
SELECT id, title, project_id, "index", deleted, deleted_at, created_at, updated_at FROM sections
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetSection(ctx context.Context, id string) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSection, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSectionsByProject = `-- name: ListSectionsByProject :many
SELECT id, title, project_id, "index", deleted, deleted_at, created_at, updated_at FROM sections
WHERE project_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListSectionsByProject(ctx context.Context, projectID sql.NullString) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Section{}
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.Index,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSection = `-- name: SoftDeleteSection :exec
UPDATE sections SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteSectionParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteSection(ctx context.Context, arg SoftDeleteSectionParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSection, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteSectionsByProject = `-- name: SoftDeleteSectionsByProject :exec
UPDATE sections SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE project_id = ? AND deleted = 0
`

type SoftDeleteSectionsByProjectParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ProjectID sql.NullString `json:"project_id"`
}

func (q *Queries) SoftDeleteSectionsByProject(ctx context.Context, arg SoftDeleteSectionsByProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSectionsByProject, arg.DeletedAt, arg.UpdatedAt, arg.ProjectID)
	return err
}

const updateSectionTitle = `-- name: UpdateSectionTitle :one
UPDATE sections SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, project_id, "index", deleted, deleted_at, created_at, updated_at
`

type UpdateSectionTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateSectionTitle(ctx context.Context, arg UpdateSectionTitleParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, updateSectionTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectID,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
