// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, 0, NULL, ?, ?
)
RETURNING id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at
`

type CreateTagParams struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	ParentID  sql.NullString `json:"parent_id"`
	Shortcut  sql.NullString `json:"shortcut"`
	Index     int64          `json:"index"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.Title,
		arg.ParentID,
		arg.Shortcut,
		arg.Index,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentID,
		&i.Shortcut,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at FROM tags
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentID,
		&i.Shortcut,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at FROM tags
WHERE deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentID,
			&i.Shortcut,
			&i.Index,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteTagParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTag, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateTagShortcut = `-- name: UpdateTagShortcut :one
UPDATE tags SET shortcut = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at
`

type UpdateTagShortcutParams struct {
	Shortcut  sql.NullString `json:"shortcut"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTagShortcut(ctx context.Context, arg UpdateTagShortcutParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTagShortcut, arg.Shortcut, arg.UpdatedAt, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentID,
		&i.Shortcut,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTagTitle = `-- name: UpdateTagTitle :one
UPDATE tags SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, parent_id, shortcut, "index", deleted, deleted_at, created_at, updated_at
`

type UpdateTagTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTagTitle(ctx context.Context, arg UpdateTagTitleParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTagTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentID,
		&i.Shortcut,
		&i.Index,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
