// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_links.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addTaskLink = `-- name: AddTaskLink :exec
INSERT OR IGNORE INTO task_links (task_id, related_task_id, relationship_type, created_at, user_id)
VALUES (?, ?, ?, ?, ?)
`

type AddTaskLinkParams struct {
	TaskID           string       `json:"task_id"`
	RelatedTaskID    string       `json:"related_task_id"`
	RelationshipType string       `json:"relationship_type"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UserID           string       `json:"user_id"`
}

func (q *Queries) AddTaskLink(ctx context.Context, arg AddTaskLinkParams) error {
	_, err := q.db.ExecContext(ctx, addTaskLink,
		arg.TaskID,
		arg.RelatedTaskID,
		arg.RelationshipType,
		arg.CreatedAt,
		arg.UserID,
	)
	return err
}

const listTaskLinks = `-- name: ListTaskLinks :many
SELECT task_id, related_task_id, relationship_type, created_at, user_id FROM task_links WHERE task_id = ? AND user_id = ?
`

type ListTaskLinksParams struct {
	TaskID string `json:"task_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListTaskLinks(ctx context.Context, arg ListTaskLinksParams) ([]TaskLink, error) {
	rows, err := q.db.QueryContext(ctx, listTaskLinks, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLink{}
	for rows.Next() {
		var i TaskLink
		if err := rows.Scan(
			&i.TaskID,
			&i.RelatedTaskID,
			&i.RelationshipType,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskLink = `-- name: RemoveTaskLink :exec
DELETE FROM task_links WHERE task_id = ? AND related_task_id = ? AND user_id = ?
`

type RemoveTaskLinkParams struct {
	TaskID        string `json:"task_id"`
	RelatedTaskID string `json:"related_task_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) RemoveTaskLink(ctx context.Context, arg RemoveTaskLinkParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskLink, arg.TaskID, arg.RelatedTaskID, arg.UserID)
	return err
}
