// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const cancelTasksByProject = `-- name: CancelTasksByProject :exec
UPDATE tasks SET status = 2, updated_at = ?
WHERE project_id = ? AND status = 0 AND deleted = 0
`

type CancelTasksByProjectParams struct {
	UpdatedAt time.Time      `json:"updated_at"`
	ProjectID sql.NullString `json:"project_id"`
}

func (q *Queries) CancelTasksByProject(ctx context.Context, arg CancelTasksByProjectParams) error {
	_, err := q.db.ExecContext(ctx, cancelTasksByProject, arg.UpdatedAt, arg.ProjectID)
	return err
}

const cascadeDeleteTasksByArea = `-- name: CascadeDeleteTasksByArea :exec
UPDATE tasks SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE area_id = ? AND deleted = 0
`

type CascadeDeleteTasksByAreaParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	AreaID    sql.NullString `json:"area_id"`
}

func (q *Queries) CascadeDeleteTasksByArea(ctx context.Context, arg CascadeDeleteTasksByAreaParams) error {
	_, err := q.db.ExecContext(ctx, cascadeDeleteTasksByArea, arg.DeletedAt, arg.UpdatedAt, arg.AreaID)
	return err
}

const cascadeDeleteTasksBySection = `-- name: CascadeDeleteTasksBySection :exec
UPDATE tasks SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE section_id = ? AND deleted = 0
`

type CascadeDeleteTasksBySectionParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	SectionID sql.NullString `json:"section_id"`
}

func (q *Queries) CascadeDeleteTasksBySection(ctx context.Context, arg CascadeDeleteTasksBySectionParams) error {
	_, err := q.db.ExecContext(ctx, cascadeDeleteTasksBySection, arg.DeletedAt, arg.UpdatedAt, arg.SectionID)
	return err
}

const completeTasksByProject = `-- name: CompleteTasksByProject :exec
UPDATE tasks SET status = 1, completed_at = ?, updated_at = ?
WHERE project_id = ? AND status = 0 AND deleted = 0
`

type CompleteTasksByProjectParams struct {
	CompletedAt sql.NullTime   `json:"completed_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ProjectID   sql.NullString `json:"project_id"`
}

func (q *Queries) CompleteTasksByProject(ctx context.Context, arg CompleteTasksByProjectParams) error {
	_, err := q.db.ExecContext(ctx, completeTasksByProject, arg.CompletedAt, arg.UpdatedAt, arg.ProjectID)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, title, notes, status, schedule, start_date, deadline, completed_at,
    "index", today_index, project_id, section_id, area_id, location_id,
    recurrence_rule, deleted, deleted_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, 0, NULL, ?, ?
)
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID             string         `json:"id"`
	Title          sql.NullString `json:"title"`
	Notes          string         `json:"notes"`
	Status         int64          `json:"status"`
	Schedule       int64          `json:"schedule"`
	StartDate      sql.NullString `json:"start_date"`
	Deadline       sql.NullString `json:"deadline"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	Index          int64          `json:"index"`
	TodayIndex     sql.NullInt64  `json:"today_index"`
	ProjectID      sql.NullString `json:"project_id"`
	SectionID      sql.NullString `json:"section_id"`
	AreaID         sql.NullString `json:"area_id"`
	LocationID     sql.NullString `json:"location_id"`
	RecurrenceRule sql.NullString `json:"recurrence_rule"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Status,
		arg.Schedule,
		arg.StartDate,
		arg.Deadline,
		arg.CompletedAt,
		arg.Index,
		arg.TodayIndex,
		arg.ProjectID,
		arg.SectionID,
		arg.AreaID,
		arg.LocationID,
		arg.RecurrenceRule,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE id = ? AND deleted = 0
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByArea = `-- name: ListTasksByArea :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE area_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasksByArea(ctx context.Context, areaID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByArea, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByLocation = `-- name: ListTasksByLocation :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE location_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasksByLocation(ctx context.Context, locationID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE project_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksBySchedule = `-- name: ListTasksBySchedule :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE schedule = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasksBySchedule(ctx context.Context, schedule int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksBySchedule, schedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksBySection = `-- name: ListTasksBySection :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE section_id = ? AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ListTasksBySection(ctx context.Context, sectionID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanTasksByArea = `-- name: OrphanTasksByArea :exec
UPDATE tasks SET area_id = NULL, updated_at = ?
WHERE area_id = ? AND deleted = 0
`

type OrphanTasksByAreaParams struct {
	UpdatedAt time.Time      `json:"updated_at"`
	AreaID    sql.NullString `json:"area_id"`
}

func (q *Queries) OrphanTasksByArea(ctx context.Context, arg OrphanTasksByAreaParams) error {
	_, err := q.db.ExecContext(ctx, orphanTasksByArea, arg.UpdatedAt, arg.AreaID)
	return err
}

const orphanTasksBySection = `-- name: OrphanTasksBySection :exec
UPDATE tasks SET section_id = NULL, updated_at = ?
WHERE section_id = ? AND deleted = 0
`

type OrphanTasksBySectionParams struct {
	UpdatedAt time.Time      `json:"updated_at"`
	SectionID sql.NullString `json:"section_id"`
}

func (q *Queries) OrphanTasksBySection(ctx context.Context, arg OrphanTasksBySectionParams) error {
	_, err := q.db.ExecContext(ctx, orphanTasksBySection, arg.UpdatedAt, arg.SectionID)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteTaskParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteTasksByProject = `-- name: SoftDeleteTasksByProject :exec
UPDATE tasks SET deleted = 1, deleted_at = ?, updated_at = ?
WHERE project_id = ? AND deleted = 0
`

type SoftDeleteTasksByProjectParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ProjectID sql.NullString `json:"project_id"`
}

func (q *Queries) SoftDeleteTasksByProject(ctx context.Context, arg SoftDeleteTasksByProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTasksByProject, arg.DeletedAt, arg.UpdatedAt, arg.ProjectID)
	return err
}

const updateTaskArea = `-- name: UpdateTaskArea :one
UPDATE tasks SET area_id = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskAreaParams struct {
	AreaID    sql.NullString `json:"area_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskArea(ctx context.Context, arg UpdateTaskAreaParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskArea, arg.AreaID, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskDeadline = `-- name: UpdateTaskDeadline :one
UPDATE tasks SET deadline = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskDeadlineParams struct {
	Deadline  sql.NullString `json:"deadline"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskDeadline(ctx context.Context, arg UpdateTaskDeadlineParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskDeadline, arg.Deadline, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskIndex = `-- name: UpdateTaskIndex :one
UPDATE tasks SET "index" = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskIndexParams struct {
	Index     int64     `json:"index"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTaskIndex(ctx context.Context, arg UpdateTaskIndexParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskIndex, arg.Index, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskLocation = `-- name: UpdateTaskLocation :one
UPDATE tasks SET location_id = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskLocationParams struct {
	LocationID sql.NullString `json:"location_id"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTaskLocation(ctx context.Context, arg UpdateTaskLocationParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskLocation, arg.LocationID, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskNotes = `-- name: UpdateTaskNotes :one
UPDATE tasks SET notes = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskNotesParams struct {
	Notes     string    `json:"notes"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTaskNotes(ctx context.Context, arg UpdateTaskNotesParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskNotes, arg.Notes, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskProject = `-- name: UpdateTaskProject :one
UPDATE tasks SET project_id = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskProjectParams struct {
	ProjectID sql.NullString `json:"project_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskProject(ctx context.Context, arg UpdateTaskProjectParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskProject, arg.ProjectID, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskRecurrence = `-- name: UpdateTaskRecurrence :one
UPDATE tasks SET recurrence_rule = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskRecurrenceParams struct {
	RecurrenceRule sql.NullString `json:"recurrence_rule"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateTaskRecurrence(ctx context.Context, arg UpdateTaskRecurrenceParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskRecurrence, arg.RecurrenceRule, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskSchedule = `-- name: UpdateTaskSchedule :one
UPDATE tasks SET schedule = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskScheduleParams struct {
	Schedule  int64     `json:"schedule"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTaskSchedule(ctx context.Context, arg UpdateTaskScheduleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskSchedule, arg.Schedule, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskSection = `-- name: UpdateTaskSection :one
UPDATE tasks SET section_id = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskSectionParams struct {
	SectionID sql.NullString `json:"section_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskSection(ctx context.Context, arg UpdateTaskSectionParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskSection, arg.SectionID, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStartDate = `-- name: UpdateTaskStartDate :one
UPDATE tasks SET start_date = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskStartDateParams struct {
	StartDate sql.NullString `json:"start_date"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskStartDate(ctx context.Context, arg UpdateTaskStartDateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStartDate, arg.StartDate, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = ?, completed_at = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	Status      int64        `json:"status"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskTitle = `-- name: UpdateTaskTitle :one
UPDATE tasks SET title = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskTitle(ctx context.Context, arg UpdateTaskTitleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskTodayIndex = `-- name: UpdateTaskTodayIndex :one
UPDATE tasks SET today_index = ?, updated_at = ?
WHERE id = ? AND deleted = 0
RETURNING id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at
`

type UpdateTaskTodayIndexParams struct {
	TodayIndex sql.NullInt64 `json:"today_index"`
	UpdatedAt  time.Time     `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateTaskTodayIndex(ctx context.Context, arg UpdateTaskTodayIndexParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskTodayIndex, arg.TodayIndex, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Schedule,
		&i.StartDate,
		&i.Deadline,
		&i.CompletedAt,
		&i.Index,
		&i.TodayIndex,
		&i.ProjectID,
		&i.SectionID,
		&i.AreaID,
		&i.LocationID,
		&i.RecurrenceRule,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
