// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package sqlc

import (
	"context"
	"database/sql"
)

const viewInbox = `-- name: ViewInbox :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at, time_slot, user_id FROM tasks
WHERE schedule = 0 AND user_id = ? AND status = 0 AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ViewInbox(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewInbox, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlot,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewLogbook = `-- name: ViewLogbook :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at, time_slot, user_id FROM tasks
WHERE status IN (1, 2) AND user_id = ? AND deleted = 0
ORDER BY completed_at DESC
`

func (q *Queries) ViewLogbook(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewLogbook, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlot,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewSomeday = `-- name: ViewSomeday :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at, time_slot, user_id FROM tasks
WHERE schedule = 2 AND user_id = ? AND status = 0 AND deleted = 0
ORDER BY "index"
`

func (q *Queries) ViewSomeday(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewSomeday, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlot,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewToday = `-- name: ViewToday :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at, time_slot, user_id FROM tasks
WHERE schedule = 1 AND user_id = ? AND status = 0 AND deleted = 0
  AND (start_date IS NULL OR start_date <= ?)
ORDER BY COALESCE(today_index, 999999), "index"
`

type ViewTodayParams struct {
	UserID    string         `json:"user_id"`
	StartDate sql.NullString `json:"start_date"`
}

func (q *Queries) ViewToday(ctx context.Context, arg ViewTodayParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewToday, arg.UserID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlot,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewUpcoming = `-- name: ViewUpcoming :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at, time_slot, user_id FROM tasks
WHERE start_date > ? AND user_id = ? AND status = 0 AND deleted = 0
ORDER BY start_date, "index"
`

type ViewUpcomingParams struct {
	StartDate sql.NullString `json:"start_date"`
	UserID    string         `json:"user_id"`
}

func (q *Queries) ViewUpcoming(ctx context.Context, arg ViewUpcomingParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewUpcoming, arg.StartDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlot,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
