// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package sqlc

import (
	"context"
	"database/sql"
)

const viewInbox = `-- name: ViewInbox :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE schedule = 0 AND status = 0 AND deleted = 0
  AND start_date IS NULL
ORDER BY "index"
`

// Inbox: unscheduled tasks with no start date set
func (q *Queries) ViewInbox(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewInbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewLogbook = `-- name: ViewLogbook :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE status IN (1, 2) AND deleted = 0
ORDER BY completed_at DESC
`

func (q *Queries) ViewLogbook(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewLogbook)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewSomeday = `-- name: ViewSomeday :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE schedule = 2 AND status = 0 AND deleted = 0
  AND start_date IS NULL
ORDER BY "index"
`

// Someday: long-term, no date, not prioritized
func (q *Queries) ViewSomeday(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewSomeday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewToday = `-- name: ViewToday :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE schedule = 1 AND status = 0 AND deleted = 0
  AND (start_date IS NULL OR start_date <= ?)
ORDER BY COALESCE(today_index, 999999), "index"
`

// Today: scheduled as anytime, with no date or start_date <= today
func (q *Queries) ViewToday(ctx context.Context, startDate sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewToday, startDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewUpcoming = `-- name: ViewUpcoming :many
SELECT id, title, notes, status, schedule, start_date, deadline, completed_at, "index", today_index, project_id, section_id, area_id, location_id, recurrence_rule, deleted, deleted_at, created_at, updated_at FROM tasks
WHERE start_date > ? AND status = 0 AND deleted = 0
  AND schedule != 2
ORDER BY start_date, "index"
`

// Upcoming: tasks with a future start date (excludes someday)
func (q *Queries) ViewUpcoming(ctx context.Context, startDate sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, viewUpcoming, startDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Status,
			&i.Schedule,
			&i.StartDate,
			&i.Deadline,
			&i.CompletedAt,
			&i.Index,
			&i.TodayIndex,
			&i.ProjectID,
			&i.SectionID,
			&i.AreaID,
			&i.LocationID,
			&i.RecurrenceRule,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
